#This is the backend CI/CD Pipeline for pushing to the project to CSC Openshift platform
image: ayufan/openshift-cli

stages:
    - testing
    - build

variables:
  OPENSHIFT_SERVER: https://rahti.csc.fi:8443/
  OPENSHIFT_DOMAIN: rahti.csc.fi
  
  # Configure this variable in Secure Variables:
  OPENSHIFT_TOKEN: "$OPENSHIFT_TOKEN"

.deploy: &deploy
  before_script:
    - cd
    - echo $CI_PROJECT_NAME
    - git clone https://gitlab.labranet.jamk.fi/digiateam/backend.git
  tags:
    - shell

eslint:
  stage: testing
  allow_failure: true
  script:
    - npm install eslint --save-dev
    - npm install eslint-plugin-react@latest --save-dev
    - ./node_modules/.bin/eslint server.js

buildProductionToOpenshift:
 stage: build
 when: manual
 script:
    - unset CI
    - npm ci
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc status
    - oc whoami
    - oc project tuhlari
    - oc start-build backend --from-repo="." --follow --wait